# wengwengweng

language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust:
      - nightly
      - beta

addons:
  apt:
    packages:
    - libasound2-dev
    - libudev-dev
    - libssl-dev

script:
  - cargo check --examples

