# wengwengweng

[package]
name = "dirty"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
description = "dirty tool kit"
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"

[dependencies]

# gfx
gl = "*"
image = "*"
tobj = "*"

# audio
rodio = "*"

# window
sdl2 = { version = "*", features = ["static-link", "bundled"] }

# file
glob = "*"

# serde
serde = { version = "*", features = ["derive"] }
serde_json = "*"

# math
rand = "*"

# misc
num = "*"
aseprite = "*"

# bindings
rlua = "*"
ketos = "*"

# macos
[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "*"

