# wengwengweng

[package]
name = "dirty"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
description = "dirty tool kit"
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"

[dependencies]
gl = "*"
image = "*"
tobj = "*"
rodio = "*"
sdl2 = { version = "*", features = ["static-link", "bundled"] }
glob = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rand = "*"
num = "*"
aseprite = "*"
rlua = "*"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "*"

[[example]]
name = "ecs"
path = "examples/ecs/ecs.rs"

