# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["tga <tga@wengwengweng.me>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"
exclude = [
	"TODO",
	"misc/",
]

[profile.dev.package."*"]
opt-level = 2

[features]
default = [
# 	"ase",
# 	"synth",
# 	"midi",
# 	"json",
# 	"bin",
]

json = [
	"serde_json",
]

bin = [
	"bincode",
]

midi = [
	"midir",
]

ase = []
synth = []

[dependencies]
random = { version = "0.7", package = "rand", features = [ "wasm-bindgen", ] }
noise = "0.6"
derive_more = "0.99"
once_cell = "1.2"
instant = { version = "0.1", features = [ "wasm-bindgen", ] }
serde = { version = "1.0", features = [ "derive", ] }

# fs
dirs-next = "1.0"
glob = "0.3"

# app
glow = "0.4"
fontdue = "0.0"
gilrs = "0.7"
image = { version = "0.23", default-features = false, features = [ "png", "jpeg", "tga", "bmp", ] }
tobj = "2.0"
gltf = "0.15"

# audio
cpal = "0.11"
puremp3 = "0.1"
lewton = "0.10"
hound = "3.4"
sfxr = "0.1"

# midi
midir = { version = "0.6", optional = true }

# json
serde_json = { version = "1.0", optional = true }

# bin
bincode = { version = "1.2", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
glutin = "0.24"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
	"console",
	"Blob",
	"Url",
	"Document",
	"Node",
	"Window",
	"Element",
	"HtmlElement",
	"HtmlCanvasElement",
	"HtmlAudioElement",
	"WebGlRenderingContext",
	"WebGl2RenderingContext",
	"MouseEvent",
	"KeyboardEvent",
	"WheelEvent",
	"AudioContext",
	"AudioBufferSourceNode",
	"AudioBuffer",
	"AudioDestinationNode",
]

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.7"

