# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["tga <tga@wengwengweng.me>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"
exclude = ["TODO"]

[profile.dev.package."*"]
opt-level = 2

[features]
default = [

	# modules
# 	"kit",
# 	"imgui",
# 	"ase",
# 	"http",
# 	"synth",
# 	"midi",
# 	"json",
# 	"bin",

	# options
# 	"gl3",

]

http = [
	"url",
	"httparse",
	"rustls",
	"webpki",
	"webpki-roots",
]

imgui = [
	"imgui_lib",
]

json = [
	"serde_json",
]

bin = [
	"bincode",
]

midi = [
	"midir",
]

ase = []
kit = []
synth = []

gl3 = []

[dependencies]
random = { version = "0.7", package = "rand" }
rayon = "1.3"
noise = "0.6"
derive_more = "0.99"
once_cell = "1.2"
owning_ref = "0.4"
num_cpus = "1.10"
serde = { version = "1.0", features = [ "derive", ] }

# fs
directories = "2.0"
glob = "0.3"

# app
glutin = "0.24"
glow = { version = "0.4.0", default-features = false }
clipboard = "0.5"
fontdue = "0.0"
gilrs = "0.7"
image = { version = "0.23", default-features = false, features = [ "png", "jpeg", "tga", "bmp", ] }
tobj = "1.0"
gltf = "0.15"

# audio
rodio = { version = "0.11", default-features = false, features = [ "vorbis", "mp3", "wav", ] }
cpal = "0.11"

# imgui
imgui_lib = { version = "0.3", optional = true, package = "imgui" }

# http
url = { version = "2.1", optional = true }
httparse = { version = "1.3", optional = true }
rustls = { version = "0.17", optional = true }
webpki = { version = "0.21", optional = true }
webpki-roots = { version = "0.19", optional = true }

# midi
midir = { version = "0.5", optional = true }

# json
serde_json = { version = "1.0", optional = true }

# bin
bincode = { version = "1.2", optional = true }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.7"

