# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["tga <tga@wengwengweng.me>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"
exclude = ["TODO"]

# [profile.release]
# lto = true
# panic = "abort"

[features]
default = [

	# modules
# 	"gkit",
# 	"synth",
# 	"physics",
# 	"imgui",
# 	"ase",
# 	"xr",
# 	"osc",
# 	"http",
# 	"json",
# 	"bin",

	# options
# 	"gl3",

]

synth = [
	"cpal",
]

http = [
	"url",
	"httparse",
	"native-tls",
]

imgui = [
	"imgui_lib",
]

xr = [
	"openxr",
]

osc = [
	"rosc",
]

json = [
	"serde_json",
]

bin = [
	"bincode",
]

physics = [
	"nphysics2d",
	"nphysics3d",
]

ase = []
gkit = []

gl3 = []

[dependencies]
random = { version = "0.7", package = "rand" }
noise = "0.6"
derive_more = "0.99"
once_cell = "1.2"
owning_ref = "0.4"
num_cpus = "1.10"
serde = { version = "1.0", features = [ "derive", ] }

# fs
directories = "2.0"
glob = "0.3"

# app
glutin = "0.23"
glow = { version = "0.4.0", default-features = false }
clipboard = "0.5"
fontdue = "0.0"
splines = "3.0"
gilrs = "0.7"
image = { version = "0.23", default-features = false, features = [ "png", "jpeg", "tga", "bmp", ] }
tobj = "0.1"
gltf = "0.15"

# audio
rodio = { version = "0.10", default-features = false, features = [ "vorbis", "mp3", "wav", ] }

# synth
cpal = { version = "0.11", optional = true }

# imgui
imgui_lib = { version = "0.3", optional = true, package = "imgui" }

# http
url = { version = "2.1", optional = true }
httparse = { version = "1.3", optional = true }

# physics
nphysics3d = { version = "0.13", optional = true }
nphysics2d = { version = "0.13", optional = true }

# osc
rosc = { version = "0.3", optional = true }

# json
serde_json = { version = "1.0", optional = true }

# bin
bincode = { version = "1.2", optional = true }

# xr
openxr = { version = "0.11", optional = true }

# rayon = "1.2"

[target.'cfg(all(not(target_os="ios"), not(target_os="android"), not(target_arch="wasm32")))'.dependencies]
native-tls = { version = "0.2", optional = true }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.7"

