# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"
exclude = ["TODO"]

# [profile.release]
# lto = true
# panic = "abort"

[features]
default = [

	# bindings
	"lua",
# 	"python",

	# modules
	"fs",
	"app",
	"img",
# 	"audio",
	"http",
	"geom",
	"physics",
	"term",
# 	"serial",
# 	"ui",

	# features
# 	"ase",
# 	"texpack",
# 	"gl3",

]

lua = [
	"rlua",
# 	"luster",
]

python = [
	"pyo3",
# 	"rustpython-vm",
]

fs = [
	"directories",
	"glob",
	"core-foundation",
]

app = [
	"glutin",
	"gilrs",
	"glow",
	"glyph_brush",
	"web-sys",
	"wasm-bindgen",
]

img = [
	"image",
	"tobj",
]

audio = [
	"rodio",
]

physics = []

http = [
	"url",
	"httparse",
	"native-tls",
]

term = [
	"console",
]

ase = [
	"aseprite",
	"serde",
	"serde_json",
]

geom = []

texpack = [
	"guillotiere",
]

gl3 = []
ui = []

[dependencies]
rand = "0.7"
derive_more = "0.15"

directories = { version = "2.0", optional = true }
glob = { version = "0.3", optional = true }

glow = { version = "0.2", optional = true }
glyph_brush = { version = "0.5", optional = true }

image = { version = "0.22", optional = true, default-features = false, features = [ "png_codec", ] }
tobj = { version = "0.1", optional = true }

rodio = { version = "0.9", optional = true, default-features = false, features = [ "vorbis", "mp3", "wav", ] }

url = { version = "2.1", optional = true }
httparse = { version = "1.3", optional = true }

aseprite = { version = "0.1", optional = true }
serde = { version = "1.0", optional = true, features = [ "derive", ] }
serde_json = { version = "1.0", optional = true }

guillotiere = { version = "0.4.2", optional = true }

rlua = { version = "0.16", optional = true }

pyo3 = { version = "0.7.0", optional = true }
# rustpython-vm = { version = "0.1.0", optional = true }

# ketos = "0.11"
# laminar = "0.2"
# rayon = "1.0"
# crossbeam = "0.7"
# sokol = "0.2"
# rayon = "1.1"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
# TODO: glutin 0.22
glutin = { version = "0.21", optional = true }

[target.'cfg(all(not(target_os="ios"), not(target_os="android"), not(target_arch="wasm32")))'.dependencies]
gilrs = { version = "0.7", optional = true }
console = { version = "0.8", optional = true }
native-tls = { version = "0.2", optional = true }
serial = { version = "0.4", optional = true }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = { version = "0.6", optional = true }

[target.'cfg(target_arch="wasm32")'.dependencies]
web-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }

