# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"

# [profile.release]
# lto = true

[features]
default = [
# 	"lua",
# 	"fs",
	"app",
	"img",
# 	"audio",
	"http",
# 	"term",
# 	"col",
# 	"ase",
]

lua = [
	"rlua",
]

fs = [
	"directories",
	"glob",
]

app = [
	"glutin",
	"gilrs",
	"glow",
]

img = [
	"image",
	"tobj",
]

audio = [
	"rodio",
]

http = [
	"url",
	"httparse",
	"native-tls",
	"rustls",
	"webpki",
	"webpki-roots",
]

term = [
	"console",
]

ase = [
	"aseprite",
	"serde",
	"serde_json",
]

col = []

[dependencies]
rand = "0.7"
derive_more = "0.15"
rayon = "1.1"

directories = { version = "2.0", optional = true }
glob = { version = "0.3", optional = true }

rlua = { version = "0.16", optional = true }

glutin = { version = "0.21", optional = true }
gilrs = { version = "0.7", optional = true }
glow = { version = "0.2", optional = true }

image = { version = "0.21", optional = true }
tobj = { version = "0.1", optional = true }

rodio = { version = "0.9", optional = true }

url = { version = "1.7", optional = true }
httparse = { version = "1.3", optional = true }
native-tls = { version = "0.2", optional = true }
rustls = { version = "0.15", optional = true }
webpki = { version = "0.19", optional = true }
webpki-roots = { version = "0.16", optional = true }

console = { version = "0.7", optional = true }

aseprite = { version = "0.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

# ketos = "0.11"
# rusttype = "0.7"
# serial = "0.4"
# laminar = "0.2"
# rayon = "1.0"
# crossbeam = "0.7"
# sokol = "0.2"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.6.4"

