# wengwengweng

[package]
name = "dirty"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
description = "dirty tool kit"
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"

[dependencies]
image = "*"
rodio = "*"
rand = "*"
gl = "*"
tobj = "*"
num = "*"
json = "*"
core-foundation = "*"
rlua = "*"
clap = "*"

[dependencies.sdl2]
version = "*"
features = ["static-link", "bundled"]

[dependencies.serde]
version  = "*"
features = ["derive"]

