# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"

[dependencies]
gl = "0.12.0"
image = "0.21.1"
tobj = "0.1.6"
rodio = "0.8.1"
glob = "0.3.0"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.38"
rand = "0.6.5"
serial = "0.4.0"
derive_more = "0.14.0"
gilrs = "0.7.1"
laminar = "0.2.2"
rusttype = "0.7.6"
glutin = "0.21.0"
directories = "1.0.2"
reqwest = "0.9.17"
rayon = "1.0.3"
crossbeam = "0.7.1"
rlua = "0.16.3"
rlua_serde = "0.3.1"
colored = "1.8.0"
# sokol = "0.2.0"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.6.4"

