# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"

[features]
default = [ "lua", "fs", "gfx", "img", "audio", "http", "term" ]

lua = [
	"rlua",
]

fs = [
	"directories",
	"glob",
]

gfx = [
	"glutin",
	"gl",
	"gilrs",
	"glow",
]

img = [
	"image",
	"tobj",
]

audio = [
	"rodio",
]

http = [
	"url",
	"httparse",
	"native-tls",
]

term = [
	"console",
]

[dependencies]
rand = "0.6"
derive_more = "0.14"

directories = { version = "2.0", optional = true }
glob = { version = "0.3", optional = true }

rlua = { version = "0.16", optional = true }

glutin = { version = "0.21", optional = true }
gl = { version = "0.12", optional = true }
gilrs = { version = "0.7", optional = true }
glow = { version = "0.1", optional = true }

image = { version = "0.21", optional = true }
tobj = { version = "0.1", optional = true }

rodio = { version = "0.8", optional = true }

url = { version = "1.7", optional = true }
httparse = { version = "1.3", optional = true }
native-tls = { version = "0.2", optional = true }

console = { version = "0.7", optional = true }

# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# ketos = "0.11"
# rusttype = "0.7"
# serial = "0.4"
# laminar = "0.2"
# rayon = "1.0"
# crossbeam = "0.7"
# sokol = "0.2"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.6.4"

