# wengwengweng

[package]
name = "dirty"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
description = "dirty tool kit"
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"

[dependencies]
image = "*"
rodio = "*"
rand = "*"
serde = "*"
gl = "*"
tobj = "*"
num = "*"
json = "*"

[dependencies.sdl2]
version = "*"
features = ["static-link", "bundled"]

