# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"

[dependencies]
gl = "0.11.0"
image = "0.21.0"
tobj = "0.1.6"
rodio = "0.8.1"
sdl2 = { version = "0.32.1", features = ["static-link", "bundled"] }
glob = "0.2.11"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
rand = "0.6.5"
serial = "0.4.0"
aseprite = "0.1.3"
derive_more = "0.14.0"
# sokol-rs = "0.2.0"
# glutin = "0.19.0"
# gilrs = "0.7.0"

ggl_derive = { path = "src/macros/ggl" }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.6.3"

