# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"

[dependencies]
gl = "0.12"
image = "0.21"
tobj = "0.1"
rodio = "0.8"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.6"
derive_more = "0.14"
gilrs = "0.7"
glutin = "0.21"
directories = "2.0"
reqwest = "0.9"
rlua = "0.16"
rlua_serde = "0.3"
ketos = "0.11"
console = "0.7"
# rusttype = "0.7"
# serial = "0.4"
# laminar = "0.2"
# rayon = "1.0"
# crossbeam = "0.7"
# sokol = "0.2"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.6.4"

