# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"

[dependencies]
gl = "*"
image = "*"
tobj = "*"
rodio = "*"
sdl2 = { version = "*", features = ["static-link", "bundled"] }
glob = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rand = "*"
num = "*"
aseprite = "*"
specs = "*"
specs-derive = "*"
hlua = "*"
ecs_derive = { path = "src/ecs/derive" }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "*"
metal = "*"

