# wengwengweng

[package]
name = "dirty"
description = "dirty tool kit"
version = "0.0.0"
authors = ["tga <tga@wengwengweng.me>"]
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"
readme = "README.md"
exclude = [
	"TODO",
	"misc/",
]

[profile.dev.package."*"]
opt-level = 2

[features]
default = [
# 	"lua",
# 	"ase",
# 	"http",
# 	"synth",
# 	"midi",
# 	"json",
# 	"bin",
]

http = [
	"url",
	"httparse",
	"rustls",
	"webpki",
	"webpki-roots",
]

lua = [
	"mlua",
]

json = [
	"serde_json",
]

bin = [
	"bincode",
]

midi = [
	"midir",
]

ase = []
synth = []

[dependencies]
random = { version = "0.7", package = "rand" }
noise = "0.6"
derive_more = "0.99"
once_cell = "1.2"
instant = { version = "0.1", features = [ "wasm-bindgen", ] }
serde = { version = "1.0", features = [ "derive", ] }

# fs
directories = "2.0"
glob = "0.3"

# app
glow = "0.4"
clipboard = "0.5"
fontdue = "0.0"
gilrs = "0.7"
image = { version = "0.23", default-features = false, features = [ "png", "jpeg", "tga", "bmp", ] }
tobj = "2.0"
gltf = "0.15"

# audio
cpal = "0.11"

# lua
mlua = { version = "0.3", optional = true }

# http
url = { version = "2.1", optional = true }
httparse = { version = "1.3", optional = true }
rustls = { version = "0.17", optional = true }
webpki = { version = "0.21", optional = true }
webpki-roots = { version = "0.19", optional = true }

# midi
midir = { version = "0.6", optional = true }

# json
serde_json = { version = "1.0", optional = true }

# bin
bincode = { version = "1.2", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
glutin = "0.24"
rodio = { version = "0.11", default-features = false, features = [ "vorbis", "mp3", "wav", ] }

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
	"console",
	"Document",
	"Node",
	"Window",
	"Element",
	"HtmlElement",
	"HtmlCanvasElement",
	"WebGlRenderingContext",
	"WebGl2RenderingContext",
	"MouseEvent",
	"KeyboardEvent",
]

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.7"

