# wengwengweng

[package]
name = "dirty"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
description = "dirty tool kit"
repository = "https://github.com/slmjkdbtl/DIRTY"
license = "Zlib"
edition = "2018"

[dependencies]
image = "*"
rodio = "*"
rand = "*"
gl = "*"
tobj = "*"
num = "*"
glob = "*"
serde_json = "*"
aseprite = "*"
rlua = "*"
sdl2 = { version = "*", features = ["static-link", "bundled"] }
serde = { version = "*", features = ["derive"] }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "*"

