# wengwengweng

[package]
name = "lua"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
edition = "2018"

[dependencies]
rlua = "*"

[dependencies.dirty]
version = "*"
path = "../engine"
features = ["col", "res"]

