# wengwengweng

[package]
name = "ecs_derive"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
syn = "0.15.26"
quote = "0.6.11"
proc-macro2 = "0.4.26"

