name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install libasound2-dev libudev-dev
    - name: install web target
      run: rustup target add wasm32-unknown-unknown
    - name: test
      run: cargo test --verbose --all-features
    - name: test web
      run: cargo test --verbose --all-features --no-run --target wasm32-unknown-unknown

